version: '3.8'

services:
  studentdatabase:
    image: mongo
    container_name: mongo-studentdb
    ports:
      - "27017:27017"
    volumes:
      - studentdb_data:/data/db

volumes:
  studentdb_data:   
    